services:

  PlateOCR:
    build: .
    container_name: plate_ocr
    image: plate_ocr:fastapi-1.0
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "8000:8000"
    restart: unless-stopped
    # 下面是使用 GPU 的，如果使用 CPU 请删去
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
