services:

  PlateOCR:
    build: .
    container_name: plate_ocr
    image: plate_ocr:fastapi-1.0
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "127.0.0.1:8002:8000"
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]